name: "build"

on:
  workflow_dispatch:
    inputs:
      action:
        description: Trigger build
        required: true
        default: "ci"
  push:
    branches:
      - feature/** # match an pushes on feature/* and feature/<any sub branch>/*
      - main
    paths-ignore: # dont run when changes made to these folders
      - .vscode/**
      - images/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo with all histrory and tags
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set VERSION variable to 1.0.${{ github.run_number }}
        run: |
          echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: setup node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "16.x"

      - name: ðŸ’Ž install cached dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: ðŸš§ install dependencies
        run: npm install

      - name: â›‘ compile extension
        run: |
          npm run compile

      - name: ðŸ§ª run tests
        run: |
          npm run test-ci

      - uses: dorny/test-reporter@v1.5.0
        with:
          name: jest tests # Name of the check run which will be created
          path: ${{github.workspace}}/test/reports/jest-*.xml # Path to test results (inside artifact .zip)
          reporter: jest-junit # Format of test results

      - name: ðŸ›  update metadata in package.json
        uses: onlyutkarsh/patch-files-action@v1.0.3
        with:
          files: "${{github.workspace}}/package.json"
          patch-syntax: |
            = /version => "${{ env.VERSION }}"
            = /displayName => "Git Config User Profiles"
            = /description => "Define multiple git config user profiles and switch them easily using status bar"

      - name: ðŸ“¦ compile and create vsix
        run: npm run package

      - name: upload vsix as artifact build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: git-config-user-profiles-${{ env.VERSION }}.vsix
          path: ${{github.workspace}}/git-config-user-profiles-${{ env.VERSION }}.vsix
